name: popcorn_portal
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  # API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
# logic
  bloc: ^8.1.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  # handle display images
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

