name: popcorn_portal
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  # API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  # logic
  bloc: ^8.1.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  # handle display images
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  # for error handling
  dartz: ^0.10.1
  # onboarding
  concentric_transition: ^1.0.3
  readmore: ^3.0.0
  #web view
  url_launcher: ^6.2.6
  webview_flutter: ^4.8.0
  #firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  dash_chat_2: ^0.0.21
  firebase_analytics: ^11.0.1
  delightful_toast: ^1.1.0
  image_picker: ^1.1.2
  get_it: ^7.7.0
  path: ^1.9.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

